name: Email Automation

on:
  workflow_dispatch:
    inputs:
      email_subject:
        description: 'Subject of the email'
        required: true
      email_body:
        description: 'Body of the email'
        required: true

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        EMAIL_SUBJECT: ${{ github.event.inputs.email_subject }}
        EMAIL_BODY: ${{ github.event.inputs.email_body }}
      run: python project.py
