name: Email Automation

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:       # Manual trigger
  repository_dispatch:     # External service trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create credentials file
      run: |
        echo "${{ secrets.CREDENTIALS_JSON }}" > credentials.json
      shell: bash

    - name: Run script
      env:
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        CREDENTIALS_PATH: ./credentials.json
        SPREADSHEET_URL: ${{ secrets.SPREADSHEET_URL }}
        DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
      run: python project.py
