name: Email Automation

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:       # Manual trigger or external trigger
    inputs:
      event_type:
        description: 'Event type for the workflow_dispatch trigger'
        required: true
        default: 'manual-trigger'
  repository_dispatch:     # External service trigger
    types: [trigger-event]     

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the exact version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Decode and write credentials file
      run: |
        echo "${{ secrets.CREDENTIALS_JSON }}" | base64 -d > credentials.json

    - name: Run script
      env:
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        CREDENTIALS_PATH: ./credentials.json
        SPREADSHEET_URL: ${{ secrets.SPREADSHEET_URL }}
        DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
      run: python project.py

    - name: Clean up credentials
      run: rm credentials.json
